apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment  
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64   # Example: Target AMD64 nodes
      tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64